### ISSUE TITLE
Estimator::goodFeatureMatching()

### ISSUE THREAD

**Issue by narutojxl** [gogojjh/M-LOAM#10]
Hi author, 
When we select good matching of feature points, is there some reference material and theory to evaluate score behind `estimator/estimator.cpp#L1483`. 
BTW,  
* estimator.cpp#L116, maybe is `eig_thre_.block(OPT_WINDOW_SIZE + 1, 0,  NUM_OF_LASER, 1)`
* initial_extrinsics.cpp#L146, according to our communication in the email, should be plus, compared with initial_extrinsics.cpp#L139

Thanks for your help and time in advance!

**Comment by gogojjh** [comment]
About good feature matching, since my paper is still under review, you can check this paper on visual SLAM:
https://sites.google.com/site/zhaoyipu/good-feature-visual-slam?authuser=0
The feature matching technique is inspired by this work.

**Comment by narutojxl** [comment]
Thanks author :), close it now.
