### ISSUE TITLE
lidarMapper::goodFeatureMatching() 

### ISSUE THREAD

**Issue by narutojxl** [gogojjh/M-LOAM#13]
Hi author, 
* When `gf_method == "fps"` in  lidarMapper::goodFeatureMatching(), lidar_mapper.h#L353, I'm curious that we don't distinguish the type(surf or corner) of the starting point `k`, which is selected randomly. Should we distinguish it ?
* lidar_mapper.h#L159,  the `res[1]` seems doesn't exist, right?
* associate_uct.hpp#L26, there is a typo, should be "plus" according to eq.45 of barfoot's paper. Thanks for your help!
![image](https://user-images.githubusercontent.com/6205343/105467391-994f5c00-5cd0-11eb-8048-5b04791bc1fd.png)

**Comment by gogojjh** [comment]
Thanks for your corrections.
1. we should distinguish it.
2. res[1] does not exist since the dimension of the residual is 1x1
3. should be plus.

Thank you again, I will fix these bugs.
