### ISSUE TITLE
如何使用两个雷达运行mloam.

### ISSUE THREAD

**Issue by shikeqin123** [gogojjh/M-LOAM#15]
作者你好，这个工作很出色，但我在使用两个雷达进行实验时出现了问题，程序虽然能够运行，但是rviz无地图出现，因此我想请教一下如何使用两个雷达运行mloam.

根据mloam_handheld.launch的内容，我提供了 `/right/velodyne_points` `/left/velodyne_points` 两个点云topic, 
然后执行`roslaunch mloam_handheld.launch`和`rviz -d mloam.rviz`. 结果却没有任何东西显示。

我需要做什么来正确运行程序？另外，m-loam应该并不需要IMU的topic吧？还是说使用bag和实时使用雷达数据有所区别呢？

**Comment by gogojjh** [comment]
Hi, thanks for your comment.
I suggesting following the README and using the script to run m-loam:
``python2 run_mloam.py -program=single_test -sequence=RHD -start_idx=0 -end_idx=2''

And then opening ``mloam_indoor.rviz'' for visualization.
IMU is not needed.

**Comment by shikeqin123** [comment]
![mloam](https://user-images.githubusercontent.com/48941485/120628823-b45c8480-c497-11eb-8b95-8305b7d88ec5.png)
I use your dataset, mloam can work, but when I use my own two vlp-16 to collect data in the room, and then run mloam failed, as shown in the figure. I can use LEGO loam and loam successfully in this room. I don't know whether I need to pre calibrate or modify some parameters?

**Comment by gogojjh** [comment]
sure, you need to modify the extrinsics in the YAML file.
