### ISSUE TITLE
How are the results on KITTI

### ISSUE THREAD

**Issue by wzey** [gogojjh/M-LOAM#16]
Hi, it is a very helpful work. I wonder how are your results on KITTI. I run mloam on kitti bag, but the number of keyframes is not equal to bag frames? I can't use kitti evaluation tool to plot path. Do you have tested on kitti?

**Comment by gogojjh** [comment]
Thanks for your interest. I have tested M-LOAM on some KITTI sequences, but have not evaluated it on the KITTI benchmark. I set the mapping frequency as 5Hz, making the output frame numbers are not equal to the groundtruth. You are recommended to modify some parameters and this M-LOAM on the KITTI.

**Comment by wzey** [comment]
Thanks for your replaying!
I find that **single_eval**   command = 'python2 $rpg_path/scripts/analyze_trajectory_single_mloam.py \
maybe you miss to upload that file? analyze_trajectory_single_mloam.py

**Comment by gogojjh** [comment]
I use this evaluation toolbox, but modify some codes (figure color, printing ...): 
https://github.com/uzh-rpg/rpg_trajectory_evaluation/blob/master/scripts/analyze_trajectory_single.py . 
You can download and use it for evaluation. The format is compatible. thanks.

**Comment by wzey** [comment]
Hi
Thanks for uploading oxford ros bag file. But I find this bag is 2730 seconds and not been divided into 5 parts like your paper mentioned.
Can you tell the start and end time in ros bag for this 5 parts?

**Comment by gogojjh** [comment]
You can use this equation to determine the start and end time: from S / 8281 * 2730 to E / 8281 * 2730.
Five bags:
S                 E               ID
1                800           bag1
800            2000         bag2
2000          4900         bag3
4900          6500         bag4
6500          8281         bag5
