### ISSUE TITLE
roslaunch 

### ISSUE THREAD

**Issue by hujiax380** [gogojjh/M-LOAM#17]
Hello professor!
     I`m totally a freshman of SLAM, could you please provide the roslaunch method to launch the code? I got deadly puzzled about the .py method. Thanks very much!

**Comment by gogojjh** [comment]
An example is: https://github.com/gogojjh/M-LOAM/blob/mloam_gf/estimator/script/rhd_main.sh 
roslaunch mloam mloam_handheld.launch \
    run_mloam:=true \
    run_mloam_mapping:=true \
    with_ua:=true \
    gf_method:=wo_gf \
    gf_ratio_ini:=1.0 \
    result_save:=true \
    bag_file:=$data_path \
    output_path:=$result_path
sleep 5

I suggest using the python method since there are several parameters that are used in the launch file.

**Comment by hujiax380** [comment]
> An example is: https://github.com/gogojjh/M-LOAM/blob/mloam_gf/estimator/script/rhd_main.sh
> roslaunch mloam mloam_handheld.launch
> run_mloam:=true
> run_mloam_mapping:=true
> with_ua:=true
> gf_method:=wo_gf
> gf_ratio_ini:=1.0
> result_save:=true
> bag_file:=$data_path
> output_path:=$result_path
> sleep 5
> 
> I suggest using the python method since there are several parameters that are used in the launch file.

I got it working! Thanks!

**Comment by 504115681** [comment]
> > An example is: https://github.com/gogojjh/M-LOAM/blob/mloam_gf/estimator/script/rhd_main.sh
> > roslaunch mloam mloam_handheld.launch
> > run_mloam:=true
> > run_mloam_mapping:=true
> > with_ua:=true
> > gf_method:=wo_gf
> > gf_ratio_ini:=1.0
> > result_save:=true
> > bag_file:=$data_path
> > output_path:=$result_path
> > sleep 5
> > I suggest using the python method since there are several parameters that are used in the launch file.
> 
> I got it working! Thanks!

Hello, did you get the saved file under the output path
