### ISSUE TITLE
python run_mloam.py error

### ISSUE THREAD

**Issue by 504115681** [gogojjh/M-LOAM#20]
Hello, thank you very much for this outstanding work. After I compile it,When starting with python run_mloam.py -program=single_test -sequence=SR -start_idx=0 -end_idx=4 , the following error occurred:
```
testing sequence: SR01
Traceback (most recent call last):
  File "run_mloam.py", line 267, in <module>
    single_test(args.start_idx, args.end_idx)
  File "run_mloam.py", line 64, in single_test
    os.environ['data_path'] = '{}/home/x/data/{}.bag'.format(os.environ['DATA_PATH'], seq_name[idx])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DATA_PATH'
```
I put the dataset under /home/x/data/，change the data_path path in run_mloam.py to {}/home/x/data/{}.bag as follows:
`    os.environ['data_path'] = '{}/home/x/data/{}.bag'.format(os.environ['DATA_PATH'], seq_name[idx])`
I didn't use Python very much before, so I don't know how to modify it. If you can help, thank you very much!!!

**Comment by gogojjh** [comment]
Hi, you can add this comment:
```export DATA_PATH=/home/x/data/```
in the terminal. And run this commend in the terminal. Thanks.

**Comment by 504115681** [comment]
> Hi, you can add this comment: `export DATA_PATH=/home/x/data/` in the terminal. And run this commend in the terminal. Thanks.

Thank you for your warm reply. I successfully ran the program and got some files under /home/x/catkin_m_loam/src/localization/rpg_trajectory_evaluation/results/handheld/calib_RHD02lab, such as:"initialization.txt"、"config_handheld.yaml"...,but I can't see the result of external parameter calibration under "others" folder (I checked the program and the result file of calibration external parameters should be stored in the "others" folder).
![66](https://user-images.githubusercontent.com/55040440/140460988-ec166561-5635-4817-8e9a-80be18d7ca4a.png)

![666](https://user-images.githubusercontent.com/55040440/140460995-f5b0fc2c-f97a-47f3-a0c8-a1af3dd57930.png)


![777777](https://user-images.githubusercontent.com/55040440/140460997-9ee37e4c-7df0-423b-98ed-90abd3da3ae0.png)
