### ISSUE TITLE
After "roslaunch mloam mloam_handheld.launch" running successfully, no results can be seen under the output_path path

### ISSUE THREAD

**Issue by 504115681** [gogojjh/M-LOAM#21]
Hello, thank you very much for this outstanding work,After "roslaunch mloam mloam_handheld.launch" running successfully, no results can be seen under the output_path path，Start the launch file command:
```
roslaunch mloam mloam_handheld.launch run_mloam:=true run_mloam_mapping:=true with_ua:=true gf_method:=wo_gf gf_ratio_ini:=1.0 result_save:=true bag_file:=/home/x/data/RHD01corridor.bag output_path:=/home/x/data/output_m_loam
```

launch partial log：
`x@x:~$ roslaunch mloam mloam_handheld.launch run_mloam:=true run_mloam_mapping:=true with_ua:=true gf_method:=wo_gf gf_ratio_ini:=1.0 result_save:=true bag_file:=/home/x/data/RHD01corridor.bag output_path:=/home/x/data/output_m_loam
... logging to /home/x/.ros/log/74fa8702-3b06-11ec-a0c0-709cd122d215/roslaunch-x-568.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://x:42509/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.12
 * /use_sim_time: True

NODES
  /
    lidar_mapper_keyframe (mloam/lidar_mapper_keyframe)
    mloam_node_rhd (mloam/mloam_node_rhd)
    rosbag (rosbag/play)
    static_tf_base_sensor_into_base_link (tf/static_transform_publisher)
    static_tf_laser_into_laser_left (tf/static_transform_publisher)
    static_tf_laser_into_laser_right (tf/static_transform_publisher)
    static_tf_world_base_into_world_sensor (tf/static_transform_publisher)
    static_tf_world_sensor_into_base_sensor (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [578]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 74fa8702-3b06-11ec-a0c0-709cd122d215
process[rosout-1]: started with pid [591]
started core service [/rosout]
process[mloam_node_rhd-2]: started with pid [597]
process[lidar_mapper_keyframe-3]: started with pid [599]
process[static_tf_world_base_into_world_sensor-4]: started with pid [600]
process[static_tf_world_sensor_into_base_sensor-5]: started with pid [601]
process[static_tf_laser_into_laser_left-6]: started with pid [606]
process[static_tf_laser_into_laser_right-7]: started with pid [612]
process[static_tf_base_sensor_into_base_link-8]: started with pid [619]
process[rosbag-9]: started with pid [624]
save result (0/1): 1 to /home/x/data/output_m_loam
with the awareness of uncertainty (0/1): 1
gf method: wo_gf, gf ratio: 1.000000
config file: /home/x/catkin_m_loam/src/M-LOAM/estimator/config/config_handheld.yaml
laser number 2
cloud_topic: /left/velodyne_points
cloud_topic: /right/velodyne_points
window_size: 4, opt_window_size: 2
fix extrinsic param 
Synchronized sensors, fix time offset
map corner resolution:0.200000, surf resolution:0.400000, surround kf resolution:1.000000
map kf radius: 30.000000, kf dis:1.000000, ori:1.000000
uct ext ratio: 1.000000
Mapping as 5.000000hz
Accurate extrinsic calibration!
extract surrounding keyframes: 0.000237ms
input surf num: 573 corner num: 719
map surf num: 0, corner num: 0
Map surf num is not enough
optimization time: 0.002609ms
current keyframes size: 1
save keyframes time: 0.012119ms
frame: 1, whole mapping time: 2.29646ms

Accurate extrinsic calibration!
corner/surf: before ds: 719, 573; after ds: 719, 573
filter time: 0.096265ms
extract surrounding keyframes: 0.499952ms
input surf num: 636 corner num: 665
map surf num: 573, corner num: 719
build time 0.123544ms

gf_method: wo_gf, num of all features: 665, sel features: 310
gf_method: wo_gf, num of all features: 636, sel features: 509
matching features time: 2.100704ms
Ceres Solver Report: Iterations: 7, Initial cost: 4.877573e+00, Final cost: 4.242189e+00, Termination: CONVERGENCE
mapping solver time: 2.043575ms

gf_method: wo_gf, num of all features: 665, sel features: 334
gf_method: wo_gf, num of all features: 636, sel features: 518
matching features time: 2.221940ms
Ceres Solver Report: Iterations: 7, Initial cost: 4.731431e+00, Final cost: 4.612786e+00, Termination: CONVERGENCE
mapping solver time: 2.289895ms
trace: 0
evaluate H: 0.432120ms
`
If you can help, thank you very much!!!

**Comment by gogojjh** [comment]
You should create a folder of ```/home/x/data/output_m_loam```, thanks.

**Comment by 504115681** [comment]
> You should create a folder of `/home/x/data/output_m_loam`, thanks.
Thank you very much for your quick reply. I have created this folder before, and then the above problem occurred.

**Comment by 504115681** [comment]
> You should create a folder of `/home/x/data/output_m_loam`, thanks.

Thank you very much for your quick reply. I have created this folder before, and then the above problem occurred.

**Comment by gogojjh** [comment]
Hi, thanks for your feedback. Please check this example in using the launch file: https://github.com/gogojjh/M-LOAM/blob/a4cde14413b7d7a7173dafe467e27e91811e7f6f/estimator/script/rhd_main.sh#L4

You need to set ```result_save:=true```. Thanks.

**Comment by 504115681** [comment]
Thank you for your reply. First I created this folder, then I modified mloam_handheld.launch, and changed result_save to true, and output_path to /home/x/data/output_m_loam. Then when I started the mloam_handheld.launch file with the roslaunch command, I also added result_save:=true output_path:=/home/x/data/output_m_loam/, and the launch file was completed, but there was still no result saved.
Some screenshots are as follows, I hope you can take a look:
![1](https://user-images.githubusercontent.com/55040440/140006443-0fdfd485-655f-40cb-853d-9d8a6fe24558.png)

![4](https://user-images.githubusercontent.com/55040440/140006460-659c55c5-03e5-43ba-ae3f-9b15b9756d98.png)

![3](https://user-images.githubusercontent.com/55040440/140006472-7485b1e5-75ca-4ea5-9e3f-ec2c9dfc29b3.png)

![5](https://user-images.githubusercontent.com/55040440/140006521-14b2c735-565b-4d22-aba0-b11d4b192a71.png)

![2](https://user-images.githubusercontent.com/55040440/140006534-803f95eb-8abf-48a7-bff2-bfb6bd1597da.png)

**Comment by gogojjh** [comment]
I think that these steps are enough for outputting results...
A hard-coded solution is just to modify the code. You can set ```MLOAM_RESULT_SAVE = true``` and set values for ````OUTPUT_FOLDER``, ```MLOAM_ODOM_PATH``` in this link and have a try: https://github.com/gogojjh/M-LOAM/blob/a4cde14413b7d7a7173dafe467e27e91811e7f6f/estimator/src/rosNodeRHD.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L237

**Comment by 504115681** [comment]
> I think that these steps are enough for outputting results... A hard-coded solution is just to modify the code. You can set `MLOAM_RESULT_SAVE = true` and set values for ````OUTPUT_FOLDER``, `MLOAM_ODOM_PATH` in this link and have a try: https://github.com/gogojjh/M-LOAM/blob/a4cde14413b7d7a7173dafe467e27e91811e7f6f/estimator/src/rosNodeRHD.cpp?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L237

Thank you very much for the solution ideas, I will try as soon as possible.
I now have a few small questions:
1. I want to know when you run the calibration code, the result will be saved after the rosbag package runs, or the result will be saved under the path after iterative optimization.
2. Please look at the red on the last picture I sent. When I run the rosbag bag: "RHD01corridor.bag", it appears. I don't know if it is normal or not. I suspect that this error caused no result output.
3. Can I run only one rosbag bag at a time, or do I have to run a series of all rosbag bags of the same type that you provide at a time. Because I only downloaded one rosbag package before: "RHD01corridor.bag", I also suspect this error.

**Comment by gogojjh** [comment]
You need to ```ctrl + c``` to shut down the prodcedure. Thanks.

**Comment by 504115681** [comment]
> You need to `ctrl + c` to shut down the prodcedure. Thanks.

Thank you for your reply. I found several problems:

1. Just creating the output folder is not enough. I need to create folders such as "traj.time.pose_graph.others.gf_pcd" under the output folder

2.OUTPUT_FOLDER cannot be obtained through launch file or terminal input, but can only be modified in the source code

I don't know why I have such a problem

Does anyone else have the same problem?

**Comment by 504115681** [comment]
> You need to `ctrl + c` to shut down the prodcedure. Thanks.

In the config_handeheld.yaml file, estimate_extrinsic parameters is set to 0 (Have an accurate extrinsic parameters.).
