### ISSUE TITLE
about the evalDegenracy in M-LOAM

### ISSUE THREAD

**Issue by DarrenWong** [gogojjh/M-LOAM#23]
Thanks for sharing the great work! I have a question about the function of evalDegenracy.

First, the eigenvectors are columns corresponding using SelfAdjointEigenSolver as you mentioned in the code
```
        Eigen::SelfAdjointEigenSolver<Eigen::Matrix<double, 6, 6> > esolver(mat_H);
        Eigen::Matrix<double, 1, 6> mat_E = esolver.eigenvalues().real(); // 6*1
        Eigen::Matrix<double, 6, 6> mat_V_f = esolver.eigenvectors().real(); // 6*6, column is the corresponding eigenvector

```
And you update the column as zero vector, the same as setting Vu (without transpose) in Eq (16) in [On Degeneracy of Optimization-based State Estimation Problems](https://www.cs.cmu.edu/~kaess/pub/Zhang16icra.pdf). I agree it is correct.
https://github.com/gogojjh/M-LOAM/blob/a4cde14413b7d7a7173dafe467e27e91811e7f6f/estimator/src/estimator/estimator.cpp#L1621
![image](https://user-images.githubusercontent.com/5771106/148162907-701f32b9-30aa-476b-8c6c-b03757e620f4.png)

But the loam and liomapping is going to set the row data of the eigenVectors, 

My question is does it have any difference in the definition of AtA? Or both codes are right? I am a little confused about the implementation of the paper.

https://github.com/laboshinl/loam_velodyne/blob/25db5dd5b2c135e779a50a11af0a53434598df7e/src/lib/BasicLaserOdometry.cpp#L581

```
            for (int i = 0; i < 6; i++)
            {
               if (matE(0, i) < eignThre[i])
               {
                  for (int j = 0; j < 6; j++)
                  {
                     matV2(i, j) = 0;
                  }
                  isDegenerate = true;
               }
```

https://github.com/hyye/lio-mapping/blob/8485a4d9c359b7e486ad019a10815ecb8fd1257f/src/point_processor/PointOdometry.cc#L600

```
          float eign_thre[6] = {10, 10, 10, 10, 10, 10};
          for (int i = 0; i < 6; i++) {
            if (mat_E(0, i) < eign_thre[i]) {
              for (int j = 0; j < 6; j++) {
                mat_V2(i, j) = 0;
              }
```

**Comment by SiyuanHuang95** [comment]
Hi DarrenWong,

I am currently meeting the same question.

In my opinion, I would prefer to start from the definition of the rank of one matrix.  And the column rank and the row rank are always equal. In this way, I guess both methods are correct.

Best

**Comment by DarrenWong** [comment]
@SiyuanHuang95  thanks for your reply. I think the eigenvectors matrix is orthogonal (Vt =V.inverse()) as the AtA is a symmetric matrix, but I am not sure the eigenvectors matrix is symmetrical?

I print the mat_V in liomapping but seems setting zero to column and row would be different results if the MLOAM,liomapping and LOAM define the same AtA.  I will check the definition of AtA from codes.   

mat_V in liomapping: 
000.00186954 0000.0077728 0-0.00165944 00000.951474 00000.307173 0000.0166376
0000.0030217 -0.000970272 00-0.0108192 000-0.305458 00000.949757 00-0.0673026
0000.0061719 0-0.00219115 00.000504121 0000.0364888 00-0.0589716 000-0.997571
000-0.996178 0000.0870256 0-0.00237417 00.000418513 000.00290444 0-0.00651202
0000.0870069 00000.994269 00-0.0615751 0-0.00755553 0-0.00252039 0-0.00180407

**Comment by SiyuanHuang95** [comment]
Hi @DarrenWong,

Thanks for your further information!

For the judgment of degenerate, only the rank information is needed and I would argue that whether a matrix is symmetrical does not affect its rank information?

But when I check the code details, the mat_V is also needed in calculating the mat_P, which I cannot understand too.

**Comment by DarrenWong** [comment]
Thanks for your information. I need some time to understand how rank affects the matrix_X in equation (18) of Zhangji's paper.

For the mat_V,

Imagine that the mat_V2 * mat_X mapping the mat_X(vector space) to another vector space(not sure if belongs to eigenspace) with matV2(linear mapping), then (mat_V)-1(mat_V2*mat_X) reverse back to mat_X_f (vector space).
