### ISSUE TITLE
question on solving iterative reighted least-squares

### ISSUE THREAD

**Issue by bugdeveloper0** [gogojjh/M-LOAM#24]
hello, i am confused about the inference of equation（2）in your paper：“Greedy-Based Feature Selection for Efficient LiDAR SLAM”.  The variab to be optimized is x, while it turns to be delta x after locally linearizing the objective function at an initial guess. It is known that delta x is calculated in the process of iterative reighted least-squares in practice. Is there a omitted step that the residual in equation (2) is transformed into a function with respect to delta x. Then the state x is calculated with optimized delta x and an initial guess. 
I am really looking forward to your reply.

**Comment by gogojjh** [comment]
Regarding your question: ''Is there a omitted step that the residual in equation (2) is transformed into a function with respect to delta x. Then the state x is calculated with optimized delta x and an initial guess.'', it should be noted that equ.(2) is the least-squares formulation of x, and this paper does not explicitly write out the formulation on delta x. 

This paper states that: ''2) is simplified as an iterative reweighed least-squares problem. Iterative methods such as Gauss-Newton or LevenbergMarquardt can offen be used to solve this problem.''. The GN method will further formulate equ.(2) as a minimization problem w.r.t. the variable delta x. Please refer to Prof. Barfoot's book: State Estimation for Robotics (http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf), Section 4.3.1 for details. 

Thanks!
