### ISSUE TITLE
ImageSegmenter::segmentCloud

### ISSUE THREAD

**Issue by minwoo0611** [gogojjh/M-LOAM#26]
Hello, author! Thanks for your effort with M-LOAM.
I have a question about segmentCloud function in image_segmenter.hpp.

**dist = sqrt(d1 * d1 + d2 * d2 - 2 * d1 * d2 * cos(alpha));
alpha = iter->first == 0 ? segment_alphax_ : segment_alphay_;
angle = atan2(d2 * sin(alpha), (d1 - d2 * cos(alpha)));**

To find the angle whether the criterion is met, first find the dist. However, in the process of finding dist, the value of alpha is not defined, and alpha is defined in the next line. **1) It is questionable whether the positions of these two lines should be swapped.**

Also, when iter->first ==0 when calculating alpha, alpha has the value of segment_alphay_. By the way, iter->first == 0 means that they have the same row value, which seems to mean that the angle corresponding to horizontal should be used. According to image_segmenter.cpp, the angle corresponding to horizontal seems to be segment_alphax_, but **2) I wonder if alphax_ and alphay_ should be interchanged.**

Thank you and I await for your answer!.

**Comment by gogojjh** [comment]
Thanks for your questions.
I refer you to read the paper https://arxiv.org/abs/2010.14294 for details.
Regarding your questions:
1. Can be swapped.
2. I think that they cannot be interchanged.

**Comment by minwoo0611** [comment]
Oh, I confused with question 2, and I perfectly understand your answer for my question.

Thanks for your answer!
