### ISSUE TITLE
after cd M-LOAM, I cann't compile the M-LOAM project!

### ISSUE THREAD

**Issue by nonlinear1** [gogojjh/M-LOAM#3]
in "2. Build M-LOAM on ROS", after "cd M-LOAM" run   "catkin build mloam" I cann't compile the project and give me the information:
![353871315](https://user-images.githubusercontent.com/19766939/103323528-31657700-4a7e-11eb-9fd4-4c2906f7580d.jpg)
I can compile the project  in "catkin_ws_M-LOAM1" directory--the top directory. Is there something wrong with my ROS environment?

**Comment by narutojxl** [comment]
* Try to delete the dirs generated in the previous step, such as `build`, `devel`, `install` and `log`, before in the `catkin_ws_M-LOAM1` dir perform `catkin build mloam`. 
* Not source other namespace before build start, such as:
>
	jxl@dell:~/m-loam-ws$ echo $ROS_PACKAGE_PATH
	/opt/ros/kinetic/share
	jxl@dell:~/m-loam-ws$

**Comment by gogojjh** [comment]
or you can directly enter the catkin_ws_xxx/src, and enter ```catkin build mloam```

**Comment by nonlinear1** [comment]
@narutojxl and @gogojjh Thank you very much.I have succeeded in compiling the project following narutojxl's instructions. But I cann't comile the project following gogojjh's instructions. And give me the following information:"[build] Error: Unable to find source space `/home/manifold/catkin_ws_M-LOAM1/src/M-LOAM/src`. I think maybe the reason is that there is no src directory in M-LOAM ". the snap screen is as follows:
![864086374](https://user-images.githubusercontent.com/19766939/103327546-ece2d700-4a8f-11eb-82b9-d51038d884e6.jpg)

**Comment by gogojjh** [comment]
Sorry for my mistakes... should enter the catkin_ws_xxx/src and ```catkin build```

**Comment by nonlinear1** [comment]
Thank you. I have succeeded in running your rhd dataset.

**Comment by jhx646018057** [comment]
> Thank you. I have succeeded in running your rhd dataset.

你好，我也遇到和你一样的问题，在cd M-LOAM后 catkin build 失败，请问你怎么解决的？我看这功能包最外层没有cmaklist文件哦

**Comment by gogojjh** [comment]
should enter the catkin_ws_xxx/src and ```catkin build```. **catkin_ws_xxx** is the ros workspace
