### ISSUE TITLE
How to set LAMBDA_THRE_CALIB ?

### ISSUE THREAD

**Issue by AdamPengG** [gogojjh/M-LOAM#31]
Hi gogojjh, there is a little problem。 Which way could we calculate the LAMBDA_THRE_CALIB ?

**Comment by gogojjh** [comment]
Hi, thanks for your questions.
LAMBDA_THRE_CALIB was set based on our real-world experiments. You can check our paper video: https://www.bilibili.com/video/BV1ur4y1K7FR?vd_source=a4da18bbe35d05e6b98862080af2b36a#reply5816869407 (1:36). We plotted the changing lambda. And you can set a proper LAMBDA_THRE_CALIB based on such analysis.
Thanks.

**Comment by AdamPengG** [comment]
![图片](https://user-images.githubusercontent.com/45864105/191404920-45768f6c-4427-4f7b-8444-23bcdec8e67d.png)
感谢您的回复！请教一下λ阈值为右下角指示器红色线边界的阈值400嘛。

**Comment by gogojjh** [comment]
对的
