### ISSUE TITLE
I wonder how to use my rosbag date?

### ISSUE THREAD

**Issue by sufjanmystery** [gogojjh/M-LOAM#35]
I have two VLP-16 equipmented like the handheld, and record the topics respectively in one rosbag. So how to run m-loam with my data?

**Comment by gogojjh** [comment]
Please check the launch file: https://github.com/gogojjh/M-LOAM/blob/mloam_gf/estimator/launch/mloam_handheld.launch

**Comment by sufjanmystery** [comment]
> Please check the launch file: https://github.com/gogojjh/M-LOAM/blob/mloam_gf/estimator/launch/mloam_handheld.launch

thanks,i have run my data succuessfully, but i have new issues:
1.when  running my data, the node always ends in the half of the bag, the parameters setted wrong?
![屏幕截图 2022-12-15 23:21:34](https://user-images.githubusercontent.com/86214195/207899130-138a0917-53b3-4560-bd57-46d5b6907b88.png)

![屏幕截图 2022-12-15 23:23:33](https://user-images.githubusercontent.com/86214195/207899354-a5fe43c1-ca37-48df-8106-b4c3e208fbf5.png)
2. where can i find the calibration results? i search the files in the results folder, but failed.

![屏幕截图 2022-12-15 23:27:30](https://user-images.githubusercontent.com/86214195/207900411-cb6d4479-1879-4052-b668-7457c97112ad.png)

![屏幕截图 2022-12-15 23:25:47](https://user-images.githubusercontent.com/86214195/207900147-3dc3139f-02ec-4716-9538-e2ebfadc697a.png)

**Comment by gogojjh** [comment]
1. It is very difficult to figure out. Could you please first indicate which line does this issue occur?
2. Calibration results can be printed via. the terminal.

**Comment by sufjanmystery** [comment]
Very thanks for your answer,but i still failed to print the  calibration results. I echo the TF topic the as below(using oxford data), but only the "/aft_mapped" transform was recorded,  can you tell me which topic or what  terminal to print the calibration results?

![屏幕截图 2022-12-16 16:38:31](https://user-images.githubusercontent.com/86214195/208058315-00a0f223-0868-49cd-8b59-79f13c6f2974.png)

**Comment by gogojjh** [comment]
You can print the variable qbl_[i] and tbl_[i] for the extrinsics from the primary Lidar to the ith Lidar
https://github.com/gogojjh/M-LOAM/blob/ff77e3550c12a3a51d67745050cccc541c3f6ec2/estimator/src/estimator/estimator.cpp#L1571
