### ISSUE TITLE
Request for Dataset

### ISSUE THREAD

**Issue by shaofury** [gogojjh/M-LOAM#39]
I wanted to do some experiments with the dataset mentioned in this article. However, I was unable to download these datasets via the website link given in the article. I would appreciate it if you could share the dataset with me.

**Comment by gogojjh** [comment]
http://gofile.me/4jm56/o2DkQ0QKa

if you have difficulty in downloading data from this link, please check the baidu wanpan link:
链接: https://pan.baidu.com/s/1N4WnwLwzxCWgxj5vw0wPXA 提取码: hmu9
