### ISSUE TITLE
Estimator::evaluateFeatJacobian()

### ISSUE THREAD

**Issue by narutojxl** [gogojjh/M-LOAM#9]
Hi author,
I'm curious about in case `ESTIMATE_EXTRINSIC == 0`, when we calculating  jacobian of corner points, it directly is `Eigen::Matrix<double, 1, 6>::Identity()`,  estimator.cpp#L1342, we don't use `LidarPureOdomEdgeFactor::Evaluate()`.  For surf points, we calculate jacobians with `LidarPureOdomPlaneNormFactor::Evaluate()`. 
Could you please give a little explaination :), thanks for your help and time!

**Comment by gogojjh** [comment]
You really pointed out a good question... the Jacobians of edge features should be also evaluated...

**Comment by narutojxl** [comment]
Thanks author :), my problem is solved, close it now.

**Comment by gogojjh** [comment]
Thanks for your detailed reading on M-LOAM. If you find any confusion or issues, please not hesitate to ask. This will help me to fix some remaining bugs in M-LOAM. Since I am currently busy with several ddls ... I will try to fix these issues ASAP.

Jianhao.

**Comment by narutojxl** [comment]
Thanks for author sharing your knowledge and your kind, i learned a lot !
